# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae442f29aa006b4e5598d0f2e7056e7b72b2a988cf8b72e94548895cc7b3d6c30bdf00adbdb899bb6a9b7cc8c4b64d00307b09960e07d3e920af3e920784b596

test:
  secret_key_base: 16805ed573a885da9acf45d039927fa72169b9ef8b8a9235a60504ce12bb2b157740c734019786d2c5895ad82d55a10e45fdc488ad3974ed54f959a561ec699c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
